/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef GUERRA_DE_TANQUE_PRIVATE_H
#define GUERRA_DE_TANQUE_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"0.1.1.118"
#define VER_MAJOR	0
#define VER_MINOR	1
#define VER_RELEASE	1
#define VER_BUILD	118
#define COMPANY_NAME	""
#define FILE_VERSION	""
#define FILE_DESCRIPTION	"Tank de guerra - DevC++"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	""
#define PRODUCT_VERSION	""

#endif /*GUERRA_DE_TANQUE_PRIVATE_H*/
